package main

import "strings"

// ============================================================================
// Layer 2: Argument layer
//
// For mapped commands, raw POSIX-ish flags are translated to the target
// OS's convention. For passthrough commands, args are passed COMPLETELY
// UNCHANGED — no dash stripping, no reordering, no interpretation.
//
// resolvedArg distinguishes:
//   - Raw=true:  a flag generated by the translator itself (e.g. "-Force").
//                Emitted into the command line as-is (syntax fragment).
//                PowerShell expressions containing user data must be built
//                only by helpers that quote every value, such as
//                pwshArrayLiteral.
//   - Raw=false: a user-supplied value (path, search string, etc.).
//                Always quoted by the exec layer to prevent injection.
// ============================================================================

type resolvedArg struct {
	Value string
	Raw   bool // true = translator-generated flag, emit as-is
}

// translateArgs converts logical args into OS-specific resolvedArgs.
// Passthrough (mapped=false) → returns rawArgs as non-raw values (all quoted).
func translateArgs(logicalCmd, osName string, rawArgs []string, mapped bool) []resolvedArg {
	if !mapped {
		out := make([]resolvedArg, 0, len(rawArgs))
		for _, a := range rawArgs {
			out = append(out, resolvedArg{Value: a, Raw: false})
		}
		return out
	}
	switch logicalCmd {
	case "ls":
		return translateLS(osName, rawArgs)
	case "rm":
		return translateRM(osName, rawArgs)
	case "rmdir":
		return translateLiteralPathCommand(osName, rawArgs)
	case "mkdir":
		return translateMkdir(osName, rawArgs)
	case "cat":
		return translateLiteralPathCommand(osName, rawArgs)
	case "cp", "mv":
		return translateCopyMove(osName, rawArgs)
	case "touch":
		return translateTouch(osName, rawArgs)
	case "echo":
		return translateEcho(osName, rawArgs)
	case "pwd":
		return passthroughResolved(rawArgs)
	default:
		return passthroughResolved(rawArgs)
	}
}

func passthroughResolved(rawArgs []string) []resolvedArg {
	out := make([]resolvedArg, 0, len(rawArgs))
	for _, a := range rawArgs {
		out = append(out, resolvedArg{Value: a, Raw: false})
	}
	return out
}

// rawFlag creates a translator-generated flag (emitted as-is, no quoting).
func rawFlag(s string) resolvedArg {
	return resolvedArg{Value: s, Raw: true}
}

// userVal creates a user-supplied value (always quoted by exec layer).
func userVal(s string) resolvedArg {
	return resolvedArg{Value: s, Raw: false}
}

// stripOneDash removes a single leading dash. Used only inside translators
// to normalize short flags for comparison — the ORIGINAL string is preserved
// for any arg that doesn't match a known flag.
//
// Note: this is intentionally NOT used to match flag variants. A bare "p"
// and a "-p" are different values to the user, even though they collapse to
// the same string after this function. Use rawArgMatches for case-sensitive
// exact-string matching of known flag forms.
func stripOneDash(s string) string {
	return strings.TrimPrefix(s, "-")
}

func translateLS(osName string, rawArgs []string) []resolvedArg {
	var out []resolvedArg
	long := false
	all := false
	endOfOptions := false
	var paths []string

	for _, a := range rawArgs {
		if endOfOptions {
			if osName == "win" {
				paths = append(paths, a)
			} else {
				out = append(out, userVal(a))
			}
			continue
		}
		switch a {
		case "--":
			endOfOptions = true
			if osName != "win" {
				out = append(out, rawFlag("--"))
			}
		case "-l":
			long = true
		case "-a":
			all = true
		case "-la", "-al":
			long = true
			all = true
		default:
			// unknown arg (including bare "l", "a", "al") → preserve as user value
			if osName == "win" {
				paths = append(paths, a)
			} else {
				out = append(out, userVal(a))
			}
		}
	}
	if osName == "win" {
		if all {
			out = append([]resolvedArg{rawFlag("-Force")}, out...)
		}
		if len(paths) > 0 {
			out = append(out, rawFlag("-LiteralPath"), rawFlag(pwshArrayLiteral(paths)))
		}
	} else {
		var flags string
		if long && all {
			flags = "-la"
		} else if long {
			flags = "-l"
		} else if all {
			flags = "-a"
		}
		if flags != "" {
			out = append([]resolvedArg{rawFlag(flags)}, out...)
		}
	}
	return out
}

func translateRM(osName string, rawArgs []string) []resolvedArg {
	var out []resolvedArg
	recursive := false
	force := false
	endOfOptions := false
	var paths []string

	for _, a := range rawArgs {
		if endOfOptions {
			if osName == "win" {
				paths = append(paths, a)
			} else {
				out = append(out, userVal(a))
			}
			continue
		}
		switch a {
		case "--":
			endOfOptions = true
			if osName != "win" {
				out = append(out, rawFlag("--"))
			}
		case "-r", "-R":
			recursive = true
		case "-f":
			force = true
		case "-rf", "-fr", "-Rf", "-fR":
			recursive = true
			force = true
		default:
			// unknown arg (including bare "f", "r", "rf") → preserve as user value.
			// Critical: a file named "f" or "-f" must reach rm as a path, not
			// be silently absorbed as a flag.
			if osName == "win" {
				paths = append(paths, a)
			} else {
				out = append(out, userVal(a))
			}
		}
	}
	if osName == "win" {
		if recursive {
			out = append([]resolvedArg{rawFlag("-Recurse")}, out...)
		}
		if force {
			out = append([]resolvedArg{rawFlag("-Force")}, out...)
		}
		if len(paths) > 0 {
			out = append(out, rawFlag("-LiteralPath"), rawFlag(pwshArrayLiteral(paths)))
		}
	} else {
		var flags string
		if recursive && force {
			flags = "-rf"
		} else if recursive {
			flags = "-r"
		} else if force {
			flags = "-f"
		}
		if flags != "" {
			out = append([]resolvedArg{rawFlag(flags)}, out...)
		}
	}
	return out
}

func translateMkdir(osName string, rawArgs []string) []resolvedArg {
	var out []resolvedArg
	endOfOptions := false
	var paths []string

	for _, a := range rawArgs {
		if endOfOptions {
			if osName == "win" {
				paths = append(paths, a)
			} else {
				out = append(out, userVal(a))
			}
			continue
		}
		switch a {
		case "--":
			endOfOptions = true
			if osName != "win" {
				out = append(out, rawFlag("--"))
			}
		case "-p":
			if osName == "win" {
				out = append([]resolvedArg{rawFlag("-Force")}, out...)
			} else {
				out = append([]resolvedArg{rawFlag("-p")}, out...)
			}
		default:
			// unknown arg (including bare "p") → preserve as user value.
			// A directory literally named "p" or "-p" must reach mkdir as a path.
			if osName == "win" {
				paths = append(paths, a)
			} else {
				out = append(out, userVal(a))
			}
		}
	}
	if osName == "win" && len(paths) > 0 {
		out = append(out, rawFlag("-Path"), rawFlag(pwshArrayLiteral(paths)))
	}
	return out
}

func translateTouch(osName string, rawArgs []string) []resolvedArg {
	// touch on Windows is handled at exec layer (composite PowerShell).
	// PowerShell's composite implementation receives paths directly, so consume
	// the first end-of-options marker instead of treating it as a filename.
	if osName == "win" {
		out := make([]resolvedArg, 0, len(rawArgs))
		endOfOptions := false
		for _, arg := range rawArgs {
			if !endOfOptions && arg == "--" {
				endOfOptions = true
				continue
			}
			out = append(out, userVal(arg))
		}
		return out
	}
	// POSIX touch needs the separator to protect dash-prefixed paths.
	return passthroughResolved(rawArgs)
}

func translateEcho(osName string, rawArgs []string) []resolvedArg {
	if osName == "win" {
		// Write-Output emits one record per argument. Join first to preserve
		// the single-line behavior of the abstract echo command.
		return []resolvedArg{userVal(strings.Join(rawArgs, " "))}
	}
	return passthroughResolved(rawArgs)
}

func translateLiteralPathCommand(osName string, rawArgs []string) []resolvedArg {
	if osName != "win" {
		return passthroughResolved(rawArgs)
	}
	paths := windowsOperands(rawArgs)
	if len(paths) == 0 {
		return nil
	}
	return []resolvedArg{rawFlag("-LiteralPath"), rawFlag(pwshArrayLiteral(paths))}
}

func translateCopyMove(osName string, rawArgs []string) []resolvedArg {
	if osName != "win" {
		return passthroughResolved(rawArgs)
	}
	operands := windowsOperands(rawArgs)
	if len(operands) < 2 {
		return passthroughResolved(operands)
	}
	sources := operands[:len(operands)-1]
	destination := operands[len(operands)-1]
	return []resolvedArg{
		rawFlag("-LiteralPath"),
		rawFlag(pwshArrayLiteral(sources)),
		rawFlag("-Destination"),
		userVal(destination),
	}
}

func windowsOperands(rawArgs []string) []string {
	out := make([]string, 0, len(rawArgs))
	endOfOptions := false
	for _, arg := range rawArgs {
		if !endOfOptions && arg == "--" {
			endOfOptions = true
			continue
		}
		out = append(out, arg)
	}
	return out
}

// ============================================================================
// Shell quoting — prevents arg splitting when args contain spaces
// ============================================================================

// pwshQuote wraps a single argument in PowerShell single-quote escaping.
// Prevents injection when args are joined into a -Command string.
func pwshQuote(s string) string {
	escaped := strings.ReplaceAll(s, "'", "''")
	return "'" + escaped + "'"
}

// shQuote wraps a single argument in POSIX shell single-quote escaping.
// Used for sh/zsh/wsl backends when building a -c command string.
func shQuote(s string) string {
	escaped := strings.ReplaceAll(s, "'", "'\\''")
	return "'" + escaped + "'"
}

func pwshArrayLiteral(values []string) string {
	quoted := make([]string, 0, len(values))
	for _, value := range values {
		quoted = append(quoted, pwshQuote(value))
	}
	return "@(" + strings.Join(quoted, ",") + ")"
}
