package main

import "strings"

// ============================================================================
// Layer 2: Argument layer
//
// For mapped commands, raw POSIX-ish flags are translated to the target
// OS's convention. For passthrough commands, args are passed COMPLETELY
// UNCHANGED — no dash stripping, no reordering, no interpretation.
//
// resolvedArg distinguishes:
//   - Raw=true:  a flag generated by the translator itself (e.g. "-Force").
//                Emitted into the command line as-is (syntax fragment).
//   - Raw=false: a user-supplied value (path, search string, etc.).
//                Always quoted by the exec layer to prevent injection.
// ============================================================================

type resolvedArg struct {
	Value string
	Raw   bool // true = translator-generated flag, emit as-is
}

// translateArgs converts logical args into OS-specific resolvedArgs.
// Passthrough (mapped=false) → returns rawArgs as non-raw values (all quoted).
func translateArgs(logicalCmd, osName string, rawArgs []string, mapped bool) []resolvedArg {
	if !mapped {
		out := make([]resolvedArg, 0, len(rawArgs))
		for _, a := range rawArgs {
			out = append(out, resolvedArg{Value: a, Raw: false})
		}
		return out
	}
	switch logicalCmd {
	case "ls":
		return translateLS(osName, rawArgs)
	case "rm":
		return translateRM(osName, rawArgs)
	case "mkdir":
		return translateMkdir(osName, rawArgs)
	case "touch":
		return translateTouch(osName, rawArgs)
	case "echo":
		return translateEcho(osName, rawArgs)
	case "cat", "cp", "mv", "pwd":
		return passthroughResolved(rawArgs)
	default:
		return passthroughResolved(rawArgs)
	}
}

func passthroughResolved(rawArgs []string) []resolvedArg {
	out := make([]resolvedArg, 0, len(rawArgs))
	for _, a := range rawArgs {
		out = append(out, resolvedArg{Value: a, Raw: false})
	}
	return out
}

// rawFlag creates a translator-generated flag (emitted as-is, no quoting).
func rawFlag(s string) resolvedArg {
	return resolvedArg{Value: s, Raw: true}
}

// userVal creates a user-supplied value (always quoted by exec layer).
func userVal(s string) resolvedArg {
	return resolvedArg{Value: s, Raw: false}
}

// stripOneDash removes a single leading dash. Used only inside translators
// to normalize short flags for comparison — the ORIGINAL string is preserved
// for any arg that doesn't match a known flag.
func stripOneDash(s string) string {
	return strings.TrimPrefix(s, "-")
}

func translateLS(osName string, rawArgs []string) []resolvedArg {
	var out []resolvedArg
	long := false
	all := false
	for _, a := range rawArgs {
		norm := stripOneDash(a)
		switch norm {
		case "l":
			long = true
		case "a":
			all = true
		case "al", "la":
			all = true
			long = true
		default:
			// unknown arg — preserve ORIGINAL value, mark as user value
			out = append(out, userVal(a))
		}
	}
	if osName == "win" {
		if all {
			out = append([]resolvedArg{rawFlag("-Force")}, out...)
		}
	} else {
		var flags string
		if long && all {
			flags = "-la"
		} else if long {
			flags = "-l"
		} else if all {
			flags = "-a"
		}
		if flags != "" {
			out = append([]resolvedArg{rawFlag(flags)}, out...)
		}
	}
	return out
}

func translateRM(osName string, rawArgs []string) []resolvedArg {
	var out []resolvedArg
	recursive := false
	force := false
	for _, a := range rawArgs {
		norm := stripOneDash(a)
		switch norm {
		case "r", "R":
			recursive = true
		case "rf":
			recursive = true
			force = true
		case "f":
			force = true
		default:
			// unknown arg — preserve ORIGINAL value (file path may start with -)
			out = append(out, userVal(a))
		}
	}
	if osName == "win" {
		if recursive {
			out = append([]resolvedArg{rawFlag("-Recurse")}, out...)
		}
		if force {
			out = append([]resolvedArg{rawFlag("-Force")}, out...)
		}
	} else {
		var flags string
		if recursive && force {
			flags = "-rf"
		} else if recursive {
			flags = "-r"
		} else if force {
			flags = "-f"
		}
		if flags != "" {
			out = append([]resolvedArg{rawFlag(flags)}, out...)
		}
	}
	return out
}

func translateMkdir(osName string, rawArgs []string) []resolvedArg {
	var out []resolvedArg
	for _, a := range rawArgs {
		norm := stripOneDash(a)
		if norm == "p" {
			if osName == "win" {
				out = append([]resolvedArg{rawFlag("-Force")}, out...)
			} else {
				out = append([]resolvedArg{rawFlag("-p")}, out...)
			}
			continue
		}
		// unknown arg — preserve original
		out = append(out, userVal(a))
	}
	return out
}

func translateTouch(osName string, rawArgs []string) []resolvedArg {
	// touch on Windows is handled at exec layer (composite PowerShell).
	// Args here are just paths — preserve original, mark as user values.
	return passthroughResolved(rawArgs)
}

func translateEcho(osName string, rawArgs []string) []resolvedArg {
	// echo args are all user values — preserve original, will be quoted.
	return passthroughResolved(rawArgs)
}

// ============================================================================
// Shell quoting — prevents arg splitting when args contain spaces
// ============================================================================

// pwshQuote wraps a single argument in PowerShell single-quote escaping.
// Prevents injection when args are joined into a -Command string.
func pwshQuote(s string) string {
	escaped := strings.ReplaceAll(s, "'", "''")
	return "'" + escaped + "'"
}

// shQuote wraps a single argument in POSIX shell single-quote escaping.
// Used for sh/zsh/wsl backends when building a -c command string.
func shQuote(s string) string {
	escaped := strings.ReplaceAll(s, "'", "'\\''")
	return "'" + escaped + "'"
}